
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { personalData } from '@/data/data'
import { Sidebar } from '@/components/Sidebar'







const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <head/>
      <body className="flex flex-col sm:flex-row" >
        <Sidebar/>
        <main className='grow-full p-16 w-full sm:basis-2/3 ml-auto'>
        {children}
        </main>
        </body>
    </html>
  )
}
